### ISSUE TITLE
grafana continues to restart. 

### ISSUE THREAD

**Issue by nswfugitive** [mihailescu2m/powerwall_monitor#1]
Hi, after killing the containers I re-ran the compose command without the -d as suggested.  Still restarting.

grafana exited with code 1
grafana exited with code 1
influxdb    | [httpd] 172.18.0.3 - - [19/Dec/2019:23:11:10 +0000] "POST /write?db=powerwall&rp=raw HTTP/1.1" 204 0 "-" "Telegraf/1.12.6" d7e95a44-22b4-11ea-8001-0242ac120002 56746
grafana exited with code 1
influxdb    | [httpd] 172.18.0.3 - - [19/Dec/2019:23:11:20 +0000] "POST /write?db=powerwall&rp=raw HTTP/1.1" 204 0 "-" "Telegraf/1.12.6" dddf605b-22b4-11ea-8002-0242ac120002 21135
influxdb    | [httpd] 172.18.0.3 - - [19/Dec/2019:23:11:30 +0000] "POST /write?db=powerwall&rp=raw HTTP/1.1" 204 0 "-" "Telegraf/1.12.6" e3d54d42-22b4-11ea-8003-0242ac120002 21328
grafana exited with code 1
influxdb    | [httpd] 172.18.0.3 - - [19/Dec/2019:23:11:40 +0000] "POST /write?db=powerwall&rp=raw HTTP/1.1" 204 0 "-" "Telegraf/1.12.6" e9ca1e01-22b4-11ea-8004-0242ac120002 19518
influxdb    | [httpd] 172.18.0.3 - - [19/Dec/2019:23:11:50 +0000] "POST /write?db=powerwall&rp=raw HTTP/1.1" 204 0 "-" "Telegraf/1.12.6" efc011bf-22b4-11ea-8005-0242ac120002 20514
grafana exited with code 1

**Comment by nswfugitive** [comment]
Don't know if it matters or not - but the grafana directory is blank excepted for the READ.md file.  Ignore the gracefully quit comment.

**Comment by mihailescu2m** [comment]
Seems to me you are having a docker permission issue, not grafana: 

try:

1. replace in powerwall.yml 1000 in `user: "1000:1000"` with your own user/group ID (run `id` command if linux and see UID/GID)
2. if 1 doesn't work, set loose permissions on the grafana folder (e.g. chmod 777 ./grafana) so that everyone can write
3. if 2 that doesn't work, remove the "user" line
4. if 3 doesn't work, try `user: "0:0"`

**Comment by nswfugitive** [comment]
Looks like 2 worked - I didn't try any of the others.
