### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by michalperth** [mihailescu2m/powerwall_monitor#28]
Hi,
I set the monitor few days ago and it worked fine. Then this morning it stopped and I was getting connection refuse from the Graphana. 
Ok, I cleared the Docker and I'm running the setup script for a second time. The second time reason is that the InfluxDB is not starting and is started at the same time ? It seems the same problem is happening this time as well.
---------------------------------------------------------------------------------------------
[+] Running 6/6
 ✔ Network powerwall-dashboard_default  Created     0.1s 
 ✔ Container influxdb           Started                              1.9s 
 ✔ Container pypowerwall    Started                              1.9s 
 ✔ Container weather411      Started                              2.0s 
 ✔ Container grafana            Started                               2.1s 
 ✔ Container telegraf            Started                               2.1s 
-----------------------------------------
Waiting for InfluxDB to start...
----------------------------------------------------------------------------------------------
The Docker is :
Client: Docker Engine - Community
 Version:           27.4.0
 API version:       1.47
 Go version:        go1.22.10
 Git commit:        bde2b89
 Built:             Sat Dec  7 10:38:58 2024
 OS/Arch:           linux/amd64
 Context:           default

Any help on that?
Thank you 
BTW: it is wanderful when it runs!

**Comment by michalperth** [comment]
It turns out it starts after a long time and then drops after few seconds, happens over and over.
It is on Ubuntu 24.04

**Comment by alechenne** [comment]
Hi,

I just checked the Tesla Energy App. Mine is worried well (periodically
refreshed) since many time. I have Homey Pro 2023, version 12.3.0-rc.7 and
Tesla Energy App v1.3.1 Experimental. I have Powerwall 2 with firmware
24.36.2.46990655.

Kind regards

--- Sent from Gmail Mobile --- Léchenne Alexandre Les Pâquerettes 16
CH-2608 Courtelary Mobile: +41 79 307 40 25 Email: ***@***.***


Le mar. 17 déc. 2024 à 08:10, michalperth ***@***.***> a
écrit :
